spring.application.name=gateway-service
server.port=8080


Eureka Client

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true



# USUARIO-SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=usuario-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/usuarios/**

# AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[1].id=auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/auth/**

# SUBASTA-SERVICE
spring.cloud.gateway.server.webflux.routes[2].id=subasta-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8087
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/subastas/**

# OFERTA-SERVICE
spring.cloud.gateway.server.webflux.routes[3].id=oferta-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8088
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/ofertas/**

# NOTIFICACION-SERVICE
spring.cloud.gateway.server.webflux.routes[4].id=notificacion-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8090
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/notificaciones/**

spring.cloud.gateway.server.webflux.routes[5].id=pescador-service
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8083/
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/pescadores/

#PAGO-SERVICE
spring.cloud.gateway.server.webflux.routes[6].id=pago-service
spring.cloud.gateway.server.webflux.routes[6].uri=http://localhost:8089/
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/pagos/

#LOTE-SERVICE
spring.cloud.gateway.server.webflux.routes[7].id=lote-service
spring.cloud.gateway.server.webflux.routes[7].uri=http://localhost:8086/
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/lotes/

#CAPTURA-SERVICE
spring.cloud.gateway.server.webflux.routes[8].id=captura-service
spring.cloud.gateway.server.webflux.routes[8].uri=http://localhost:8085/
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/capturas/

#ESPECIE-SERVICE
spring.cloud.gateway.server.webflux.routes[9].id=especie-service
spring.cloud.gateway.server.webflux.routes[9].uri=http://localhost:8084/
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/especies/**